leaf-domain-d-0: ./../../nats-server -c ./../conf/leaf-domain-d-0.conf -D
leaf-domain-d-1: ./../../nats-server -c ./../conf/leaf-domain-d-1.conf -D
leaf-domain-d-2: ./../../nats-server -c ./../conf/leaf-domain-d-2.conf -D