leaf-domain-c-0: ./../../nats-server -c ./../conf/leaf-domain-c-0.conf -D
leaf-domain-c-1: ./../../nats-server -c ./../conf/leaf-domain-c-1.conf -D
leaf-domain-c-2: ./../../nats-server -c ./../conf/leaf-domain-c-2.conf -D